# Le matrici in PyTorch

In [1]:
import torch
import torch.nn.functional as F

Le matrici in PyTorch sono chiamati **tensori** e appartengono alla classe `torch.tensor`.

Creiamo un primo tensore di esempio con tutti i valori a zero.



In [2]:
Z = torch.zeros((3,3))
Z

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

Confermiamo la forma di questa matrice con il metodo `shape`

In [3]:
Z.shape

torch.Size([3, 3])

Possiamo creare una matrice con tutti i valori ad 1.

In [4]:
U = torch.ones((2,2))
U

tensor([[1., 1.],
        [1., 1.]])

Oppure possiamo creare una matrice esplicitando i valori.

In [5]:
M = torch.tensor([[0.1, 0.2, 0.3],[0.4, 0.5, 0.6]])
M

tensor([[0.1000, 0.2000, 0.3000],
        [0.4000, 0.5000, 0.6000]])

In questo caso la matrice ha 2 righe e 3 colonne e quindi shape 2x3

In [6]:
M.shape

torch.Size([2, 3])

Possiamo anche inizializzare una matrice con valori casuali.

In [7]:
R = torch.randn((4,8))
R

tensor([[ 1.3547, -1.4677,  0.7367,  0.5269,  1.0975,  1.4754,  1.3930, -0.7157],
        [ 0.9203,  1.7040, -0.1683, -0.1354, -0.9271,  0.1753,  0.6226,  0.4130],
        [ 1.7095, -0.4345, -0.1505,  0.6441,  0.5831,  0.2222,  0.1867,  3.0420],
        [ 0.1594, -1.9500,  0.6139, -0.1554,  0.9564, -1.0257,  1.1587, -0.5413]])

## Matematica e operazioni su matrici

Sulle matrici si possono eseguire tutte le operazioni matematiche comuni, come somma, sottrazione, moltiplicazione, ecc.

Vi sono però alcune regole da seguire. Forma e dimensioni delle matrici devono essere compatibili.

Per esempio per sommare due matrici A e B devono avere la stessa forma e dimensione.

In [8]:
A = torch.randn((4,4))
B = torch.randn((4,4))
C = A + B
C

tensor([[-1.5144, -3.0752, -0.8546,  0.6761],
        [-2.1107, -0.7745,  1.5789, -1.4648],
        [ 0.0490,  1.1983, -0.4710, -0.6167],
        [ 0.4256,  0.2349, -1.2178,  1.9153]])

Per le moltiplicazioni esistono due tipi di moltiplicazioni

* la moltiplicazione per elementi (in questo caso le matrici devono avere le stesse dimensioni)
* la moltiplicazione algebrica tra matrici (in questo caso il numero di colonne della matrice a sinistra dell'operazione deve essere uguale al numero di righe della matrice a destra)

Iniziamo con la moltiplicazione per elementi

In [9]:
A = torch.randn((4,8))
B = torch.randn((4,8))
C = A * B
C

tensor([[ 0.1867,  0.9916, -0.0481,  0.0865,  0.0839, -0.1135, -0.8296, -1.9390],
        [ 1.3533,  2.4273,  0.1182,  0.1204, -0.3544, -0.2613, -0.1169,  0.9158],
        [-1.5911, -0.3178,  0.2344, -0.0459, -0.3823,  0.2215,  0.0472,  0.3310],
        [ 0.2812,  0.0693,  0.2531, -2.1891, -0.1290, -0.0582,  0.3813,  0.3186]])

Ma se ora provassi la moltiplicazione algebrica `@` non funzionerebbe

In [10]:
A @ B

RuntimeError: mat1 and mat2 shapes cannot be multiplied (4x8 and 4x8)

In questo caso però possiamo usare un'altra operazione, la *trasposizione* con il metodo `T`, su una delle due per ottenere la condizione di uguaglianza tra righe e colonne.

In [11]:
B.T.shape

torch.Size([8, 4])

In [12]:
A @ B.T

tensor([[-1.5815,  2.5366, -5.4461, -1.8329],
        [-4.4337,  4.2024,  3.0479,  0.0986],
        [ 1.0708, -1.1396, -1.5030, -0.7540],
        [ 0.4364,  0.5937,  0.8032, -1.0728]])

## Auto differenziazione

In [15]:
x = torch.ones(4)  # input
y = torch.tensor([0.0, 1.0])  # output atteso
w = torch.randn(4, 2, requires_grad=True)
b = torch.randn(2, requires_grad=True)
z = x @ w +b
loss = F.binary_cross_entropy_with_logits(z, y)


In [16]:
print(f"Funzione di calcolo del gradiente per z = {z.grad_fn}")
print(f"Funzione di calcolo del gradiente per la loss = {loss.grad_fn}")

Funzione di calcolo del gradiente per z = <AddBackward0 object at 0x7e11e2379660>
Funzione di calcolo del gradiente per la loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x7e11e23799c0>


In [17]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[ 0.4529, -0.4105],
        [ 0.4529, -0.4105],
        [ 0.4529, -0.4105],
        [ 0.4529, -0.4105]])
tensor([ 0.4529, -0.4105])
